FROM python:3.9-slim

COPY /app/__init__.py /code/app/
COPY /app/common/ /code/app/common/
COPY /app/api/ /code/app/api/

RUN pip install -r /code/app/api/requirements.txt
 
EXPOSE 5001

ENV PYTHONPATH /code

# config settings: https://docs.gunicorn.org/en/stable/settings.html#config
WORKDIR /code/app/api/
CMD gunicorn -c gunicorn.conf create_order_api:app
